# Write a program to input eight numbers from the user and display all the unique number (once)
num1=int(input("Enter number one\n"))
num2=int(input("Enter number two\n"))
num3=int(input("Enter number three\n"))
num4=int(input("Enter number four\n"))
num5=int(input("Enter number five\n"))
num6=int(input("Enter number six\n"))
num7=int(input("Enter number seven\n"))
num8=int(input("Enter number eight\n"))
s={num1, num2, num3, num4, num5, num6, num7, num8 }
print(s)